### ISSUE TITLE
App backup restore not possible after using the module. 

### ISSUE THREAD

**Issue by dzver123** [Xposed-Modules-Repo/com.varuns2002.disable_flag_secure#3]
Hello,

I am using LSPatch to modify Viber apk, so I can plug in the module there. When I install the resulted apk, and get back to the app, it does not recognize the chats and images backup, stored in Gdrive, therefore does not restore them. 

I am assuming that the repackaging changes something and Viber then cannot tie the existing backup with the viber instance modified from LSPatch.

Any suggestions how can I overcome that?

I saw some options in LSPatch,

1. Override version Code
2. Signature Bypass with 3 options:
2.1 Iv0: Off
2.2. Iv1: Bypass PM
2.3. Iv2: Bypass PM + openat (libc)

Would any of these help?

CC @VarunS2002

**Comment by VarunS2002** [comment]
@dzver123 
This problem is regarding how LSPatch works. I am not that well-versed with its workings and signature issues which Viber is detecting and therefore I won't be able to help you :(
Sorry for the late reply.
